# Generated by Django 5.0.6 on 2024-06-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantManagement', '0005_table_count'),
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurants',
            field=models.ManyToManyField(related_name='staff_members', to='RestaurantManagement.restaurant'),
        ),
    ]
