# Generated by Django 5.0.6 on 2024-06-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('restaurant_owner', 'Restaurant Owner'), ('restaurant_staff', 'Restaurant Staff'), ('marketing_staff', 'Marketing Staff'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
